name: "Docker Release"

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      dockerfile:
        type: string
        default: "./Dockerfile"
        required: false
      latest:
        type: string
        default: 'false'
        required: false
      force-latest:
        type: boolean
        default: false
        required: false
      latest-on-branch:
        type: string
        default: ''
        required: false
      tag-sha:
        type: boolean
        default: false
        required: false
      build-args:
        type: string
        default: ''
        required: false
      manual-tag:
        type: string
        default: ''
        required: false
      platforms:
        required: false
        default: "linux/amd64"
        description: "Comma separated list of platforms for docker buildx (eg. linux/amd64,linux/arm64)"
        type: string
      ref:
        required: false
        description: >
          The branch, tag or SHA to checkout. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that
          event.  Otherwise, uses the default branch.
        type: string
    secrets:
      docker_username:
        required: false
      docker_password:
        required: false
      docker_github_token:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
 
    - name: Manual Tag Config
      id: manualmeta
      uses: actions/github-script@v6
      env:
        INPUT_FORCE_LATEST: "${{ inputs.force-latest }}"
        INPUT_MANUAL_TAG: "${{ inputs.manual-tag }}"
        INPUT_LATEST_ON_BRANCH: "${{ inputs.latest-on-branch }}"
      with:
        script: |
          const { INPUT_FORCE_LATEST, INPUT_MANUAL_TAG, INPUT_LATEST_ON_BRANCH } = process.env

          output = []

          if (INPUT_FORCE_LATEST == "true") {
            output.push(`type=raw,value=latest,enable=true`)
          }

          if (INPUT_MANUAL_TAG != "") {
            output.push(`type=raw,value=${INPUT_MANUAL_TAG},enable=true`)
          }

          if (INPUT_LATEST_ON_BRANCH == "{{is_default_branch}}") {
            output.push(`type=raw,value=latest,enable={{is_default_branch}}`)
          } else if (INPUT_LATEST_ON_BRANCH == "refs/heads/${context.ref}") {
            output.push(`type=raw,value=latest,enable=true`)
          }

          core.setOutput('config-tags', output.join("\n"))

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.image }}
        flavor: |
          latest=${{ inputs.latest }}
        tags: |
          type=semver,pattern={{version}}
          type=sha,enable=${{ inputs.tag-sha }}
          type=ref,event=pr
          ${{ steps.manualmeta.outputs.config-tags }}

    - name: Set up QEMU
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    - name: Docker Login (Docker Hub)
      uses: docker/login-action@v2
      env:
        DOCKER_USERNAME: ${{ secrets.docker_username }}
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
      if: ${{ (env.DOCKER_USERNAME != '') && (env.DOCKER_PASSWORD != '') }}
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - name: Docker Login (GitHub Container Registry)
      uses: docker/login-action@v2
      env:
        DOCKER_GITHUB_TOKEN: ${{ secrets.docker_github_token }}
      if: ${{ env.DOCKER_GITHUB_TOKEN != '' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.docker_github_token }}

    - name: Build and Push Docker image
      if: ${{ steps.meta.outputs.tags != '' }}
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
