name: "Docker Release"

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      dockerfile:
        type: string
        default: "./Dockerfile"
        required: false
      latest:
        type: string
        default: 'false'
        required: false
      force-latest:
        type: boolean
        default: false
        required: false
      latest-on-branch:
        type: string
        default: ''
        required: false
      tag-date:
        type: string
        default: ""
        required: false
      enable-tag-sha:
        type: boolean
        default: false
        required: false
      enable-tag-semver:
        type: boolean
        default: true
        description: "Add semver tag matching commit ref (major.minor.patch)"
        required: false
      enable-tag-shortsemver:
        type: boolean
        default: true
        description: "Add semver short tag matching commit ref (major.minor)"
        required: false
      build-args:
        type: string
        default: ''
        required: false
      manual-tag:
        type: string
        default: ''
        required: false
      make-targets:
        type: string
        default: ""
        required: false
      platforms:
        required: false
        default: "linux/amd64"
        description: "Comma separated list of platforms for docker buildx (eg. linux/amd64,linux/arm64)"
        type: string
      ref:
        required: false
        description: >
          The branch, tag or SHA to checkout. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that
          event.  Otherwise, uses the default branch.
        type: string
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false
      DOCKER_GITHUB_TOKEN:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Run Make Targets
      if: ${{ inputs.make-targets != '' }}
      run: make ${{ inputs.make-targets }}

    - name: Create a date tag
      if: ${{ inputs.tag-date != '' }}
      id: date
      env:
        INPUT_TAGDATE: "${{ inputs.tag-date }}"
      run: |
        export TZ='Australia/Queensland'
        echo "tag=$(date +"${INPUT_TAGDATE}")" | tee "${GITHUB_OUTPUT}"

    - name: Manual Tag Config
      id: manualmeta
      uses: actions/github-script@v7
      env:
        INPUT_FORCE_LATEST: "${{ inputs.force-latest }}"
        INPUT_MANUAL_TAG: "${{ inputs.manual-tag }}"
        INPUT_LATEST_ON_BRANCH: "${{ inputs.latest-on-branch }}"
        OUTPUT_DATETAG: "${{ steps.date.outputs.tag }}"
      with:
        script: |
          const { INPUT_FORCE_LATEST, INPUT_MANUAL_TAG, INPUT_LATEST_ON_BRANCH, OUTPUT_DATETAG } = process.env

          output = []

          if (INPUT_FORCE_LATEST == "true") {
            output.push(`type=raw,value=latest,enable=true`)
          }

          if (INPUT_MANUAL_TAG != "") {
            output.push(`type=raw,value=${INPUT_MANUAL_TAG},enable=true`)
          }

          if (INPUT_LATEST_ON_BRANCH == "{{is_default_branch}}") {
            output.push(`type=raw,value=latest,enable={{is_default_branch}}`)
          } else if (INPUT_LATEST_ON_BRANCH == "refs/heads/${context.ref}") {
            output.push(`type=raw,value=latest,enable=true`)
          }

          if (OUTPUT_DATETAG != "") {
            output.push(`type=raw,value=${OUTPUT_DATETAG},enable=true`)
          }

          core.setOutput('config-tags', output.join("\n"))

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image }}
        flavor: |
          latest=${{ inputs.latest }}
        tags: |
          type=sha,enable=${{ inputs.enable-tag-sha }}
          type=semver,pattern={{version}},enable=${{ inputs.enable-tag-semver }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ inputs.enable-tag-shortsemver }}
          type=ref,event=pr
          ${{ steps.manualmeta.outputs.config-tags }}

    - name: Set up QEMU
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Cache Docker Buildx layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Login (Docker Hub)
      uses: docker/login-action@v3
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ (env.DOCKER_USERNAME != '') && (env.DOCKER_PASSWORD != '') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Login (GitHub Container Registry (Specific Token))
      uses: docker/login-action@v3
      env:
        DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      if: ${{ env.DOCKER_GITHUB_TOKEN != '' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

    - name: Docker Login (GitHub Container Registry (Ephemeral Token))
      uses: docker/login-action@v3
      env:
        DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      if: ${{ env.DOCKER_GITHUB_TOKEN == '' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      if: ${{ steps.meta.outputs.tags != '' }}
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Adding Docker Image Markdown Summary
      if: ${{ steps.meta.outputs.tags != '' }}
      run: |
        echo "### Docker Image Deployed to Registry 🚀" >> "${GITHUB_STEP_SUMMARY}"
        echo "" >> "${GITHUB_STEP_SUMMARY}"
        echo "${{ steps.meta.outputs.tags }}" >> "${GITHUB_STEP_SUMMARY}"
